# -*- coding: utf-8 -*-
"""Tarbajo de Jean

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bp-fZXvFMwhlyxTmAXThWAm8rZaZM3v
"""

# -*- coding: utf-8 -*-
"""Sistema de Gestión de Personas"""

import json

class Persona:
    contador_personas = 0

    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad
        Persona.contador_personas += 1

    def saludar(self):
        return f"Hola, soy {self.nombre} y tengo {self.edad} años."

    def to_dict(self):
        return {
            "tipo": "Persona",
            "nombre": self.nombre,
            "edad": self.edad
        }

    def __str__(self):
        return f"Persona | Nombre: {self.nombre}, Edad: {self.edad}"


class Estudiante(Persona):
    def __init__(self, nombre, edad, carrera):
        super().__init__(nombre, edad)
        self.carrera = carrera

    def to_dict(self):
        data = super().to_dict()
        data["tipo"] = "Estudiante"
        data["carrera"] = self.carrera
        return data

    def __str__(self):
        return f"Estudiante | {self.nombre}, {self.edad} años, Carrera: {self.carrera}"


class Empleado(Persona):
    def __init__(self, nombre, edad, salario):
        super().__init__(nombre, edad)
        self.salario = salario

    def to_dict(self):
        data = super().to_dict()
        data["tipo"] = "Empleado"
        data["salario"] = self.salario
        return data

    def __str__(self):
        return f"Empleado | {self.nombre}, {self.edad} años, Salario: ${self.salario}"


# ---------------- FUNCIONES ---------------- #

def pedir_entero(msg):
    while True:
        try:
            return int(input(msg))
        except ValueError:
            print("❌ Ingresa un número entero.")

def pedir_flotante(msg):
    while True:
        try:
            return float(input(msg))
        except ValueError:
            print("❌ Ingresa un número válido.")

def guardar_archivo(personas):
    with open("personas.json", "w", encoding="utf-8") as f:
        json.dump([p.to_dict() for p in personas], f, indent=4)
    print("✅ Datos guardados correctamente.")

def cargar_archivo():
    personas = []
    try:
        with open("personas.json", "r", encoding="utf-8") as f:
            datos = json.load(f)
            for d in datos:
                if d["tipo"] == "Estudiante":
                    personas.append(Estudiante(d["nombre"], d["edad"], d["carrera"]))
                elif d["tipo"] == "Empleado":
                    personas.append(Empleado(d["nombre"], d["edad"], d["salario"]))
                else:
                    personas.append(Persona(d["nombre"], d["edad"]))
        print("✅ Datos cargados correctamente.")
    except FileNotFoundError:
        print("❌ No existe archivo para cargar.")
    return personas

def mostrar_estadisticas(personas):
    if not personas:
        print("No hay datos.")
        return

    promedio = sum(p.edad for p in personas) / len(personas)
    estudiantes = sum(isinstance(p, Estudiante) for p in personas)
    empleados = sum(isinstance(p, Empleado) for p in personas)

    print("\n📊 ESTADÍSTICAS")
    print(f"Total de personas: {len(personas)}")
    print(f"Promedio de edad: {promedio:.1f}")
    print(f"Estudiantes: {estudiantes}")
    print(f"Empleados: {empleados}")


# ---------------- PROGRAMA PRINCIPAL ---------------- #

personas = []

while True:
    print("\n--- MENÚ ---")
    print("1. Agregar Persona")
    print("2. Agregar Estudiante")
    print("3. Agregar Empleado")
    print("4. Mostrar personas")
    print("5. Buscar por nombre")
    print("6. Eliminar persona")
    print("7. Mostrar estadísticas")
    print("8. Guardar datos")
    print("9. Cargar datos")
    print("0. Salir")

    opcion = input("Opción: ")

    if opcion == "1":
        personas.append(Persona(input("Nombre: "), pedir_entero("Edad: ")))

    elif opcion == "2":
        personas.append(Estudiante(
            input("Nombre: "),
            pedir_entero("Edad: "),
            input("Carrera: ")
        ))

    elif opcion == "3":
        personas.append(Empleado(
            input("Nombre: "),
            pedir_entero("Edad: "),
            pedir_flotante("Salario: ")
        ))

    elif opcion == "4":
        for i, p in enumerate(personas):
            print(f"{i} → {p}")

    elif opcion == "5":
        nombre = input("Nombre a buscar: ").lower()
        encontrados = [p for p in personas if nombre in p.nombre.lower()]
        for p in encontrados:
            print(p)

    elif opcion == "6":
        idx = pedir_entero("Índice a eliminar: ")
        if 0 <= idx < len(personas):
            eliminado = personas.pop(idx)
            print(f"🗑️ Eliminado: {eliminado.nombre}")
        else:
            print("❌ Índice inválido.")

    elif opcion == "7":
        mostrar_estadisticas(personas)

    elif opcion == "8":
        guardar_archivo(personas)

    elif opcion == "9":
        personas = cargar_archivo()

    elif opcion == "0":
        print("👋 Programa finalizado.")
        break

    else:
        print("❌ Opción no válida.")